# Generated by Django 4.2.3 on 2023-07-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labsecond', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='my_picture')),
                ('task_attachments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labsecond.task')),
            ],
        ),
    ]
