# Generated by Django 4.0.5 on 2023-07-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
