# Generated by Django 4.2.3 on 2023-07-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
        migrations.CreateModel(
            name='TaskAttachments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('Task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.task')),
            ],
        ),
    ]
