# Generated by Django 4.2.3 on 2023-07-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('Task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.taskcategory'),
        ),
    ]
